-- CREATE TABLE legal_person
-- (
--     id                          BIGINT NOT NULL,
--     cnpj                        VARCHAR(255),
--     social_reason               VARCHAR(255),
--     cpf_establishment_contact   VARCHAR(255),
--     name_establishment_contact  VARCHAR(255),
--     email_establishment_contact VARCHAR(255),
--     CONSTRAINT pk_legalperson PRIMARY KEY (id)
-- );
